### ISSUE TITLE
MS Apps: Missing dependency files and inconsistent parameters

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#111]
For the ms app workload's extended tests: when _use_test_file_ is set to true:
- Excel does not require a second parameter, and the excel file to use is found in wa repository
- Powerpoint does not require a second parameter, and the ppt file is **not** found in the wa repository
- MSword **does** require a second parameter (_test_file_), and the word file is **not** found in the wa repository

**Comment by muendelezaji** [comment]
No problem with parameters so considering this fixed for Word. Test file that can be committed to repo is still TBD.
