### ISSUE TITLE
workload wa dependency should be automatic

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#114]
example workload: excel
Excel has a spreadsheet dependency when use_test_file is true. This file can be found in the wa repository, but is not using the current wa dependency methods so one has to manually copy the file over to the ~/.workload_automation/dependencies folder.
bbench workload is an example of a workload that contains a dependency, which automatically gets placed in the correct dependency directory. as such all workloads uxperf creates that has a dependency stored within wa itself, should use this method, and not use a manual method of setting it up

**Comment by muendelezaji** [comment]
Fixed for word in #121
