### ISSUE TITLE
Create Powerpoint document suitable for the MS Powerpoint and ideally the Slides workload

### ISSUE THREAD

**Issue by jimboatarm** [jimboatarm/workload-automation#141]
The workloads themselves may also require modification to accommodate the new test doc.  This doc should be added to the new github repo that will be created.

**Comment by johnrchrdsn** [comment]
This is the test doc I used for the powerpoint workload. Needs testing on googleslides.
[uxperf_test_doc.pptx](https://github.com/jimboatarm/workload-automation/files/358987/uxperf_test_doc.pptx)

**Comment by muendelezaji** [comment]
Tested on Slides, looks OK. Added a step to copy the file to dependencies in pull #143
