### ISSUE TITLE
Create method to allow a user to pull the WA dependencies repo to their local setup

### ISSUE THREAD

**Issue by jimboatarm** [jimboatarm/workload-automation#142]
Sergei suggested a script to pull the repo and then install the assets in the correct location for each workload.

**Comment by muendelezaji** [comment]
@jimboatarm @setrofim
Do we want to download assets either:
1. As part of WA setup/installation
   - Get all assets at once
   - Larger, longer download of files that will potentially never be used
2. On first-run of a workload
   - Get assets for individual workloads on-demand
   - Some workloads will be "incomplete", and would require a sizeable download on first-run

**Comment by jimboatarm** [comment]
Get everything at once.   The customers we expect to use this will run all the test cases as a batch.

**Comment by muendelezaji** [comment]
Now in upstream - see ARM-software#219
