### ISSUE TITLE
Improvement: move broadcast to wa device

### ISSUE THREAD

**Issue by mcgeagh** [jimboatarm/workload-automation#169]
a lot of workloads perform this:
`self.device.execute('am broadcast -a android.intent.action.MEDIA_MOUNTED -d file:///sdcard')`

seems worth abstracting that into the self.device class of wa, perhaps called self.device.broadcast()

**Comment by johnrchrdsn** [comment]
This change is now on the upstream. See b510b310527e11fe951a3842e470d8391ff8a759. Closing
