### ISSUE TITLE
Remove the save operations in Photos and instead cancel the saving of all edits at each stage

### ISSUE THREAD

**Issue by jimboatarm** [jimboatarm/workload-automation#37]
At each stage of the workload an image is selected from the gridview, edited and saved back to the device.  This means that subsequent tests pick up an edited image.  On the Yoga device this actually results in a failure because the image gets iteratively rotated/cropped to such a small size the app complains it is less than 50k.

Instead, we should discard edits so that the images listed in the gridview remain unchanged for all iterations of the test.

**Comment by johnrchrdsn** [comment]
I've kept the save step in this workload but now we remove the edited (and saved) images after each iteration. This will prevent the same image being cropped when running multiple iterations. This was done in commit: 9393bfb

**Comment by jimboatarm** [comment]
Small problem with the change you made.  Teardown doesn't run per iteration.  It only runs at the end of the entire run.  It should work if you move this to update_result.  Please make this change and check it works.  You should be able to verify it by viewing the images gallery during the runs and ensuring there are always only 5.

**Comment by johnrchrdsn** [comment]
I think you might be confusing finalize with teardown. I see the teardown operation happening per iteration in my testing?

**Comment by jimboatarm** [comment]
I'm going with what the manual says.  http://pythonhosted.org/wlauto/writing_extensions.html#adding-a-workload.  Check with Sergei please.

**Comment by jimboatarm** [comment]
My bad.  You're correct.
