### ISSUE TITLE
googleplaybooks crashes on all iterations

### ISSUE THREAD

**Issue by jimboatarm** [jimboatarm/workload-automation#41]
This happens when it reaches the search box step to find the first sample book in the store.

INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload 1 googleplaybooks (iteration 1)
INFO        Setting up
INFO        Executing
ERROR    Error while running workload:
ERROR       INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.googleplaybooks.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googleplaybooks.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: Could not find "com.google.android.apps.books:id/search_src_text" "android.widget.EditText"
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:120)
ERROR       at com.arm.wlauto.uiauto.googleplaybooks.UiAutomation.searchForBook(UiAutomation.java:129)
ERROR       at com.arm.wlauto.uiauto.googleplaybooks.UiAutomation.runUiAutomation(UiAutomation.java:56)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googleplaybooks.UiAutomation
ERROR    INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Could not find "com.google.android.apps.books:id/search_src_text" "android.widget.EditText"
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByResourceId(BaseUiAutomation.java:120)
ERROR       at com.arm.wlauto.uiauto.googleplaybooks.UiAutomation.searchForBook(UiAutomation.java:129)
ERROR       at com.arm.wlauto.uiauto.googleplaybooks.UiAutomation.runUiAutomation(UiAutomation.java:56)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Test results for WatcherResultPrinter=.E
ERROR    Time: 11.86
ERROR  
ERROR    FAILURES!!!
ERROR    Tests run: 1,  Failures: 0,  Errors: 1

**Comment by johnrchrdsn** [comment]
This should of been fixed in e39b279
