### ISSUE TITLE
googleslides crashes at the end of the test run

### ISSUE THREAD

**Issue by jimboatarm** [jimboatarm/workload-automation#42]
This happens after the final slide 'The END - Any questions' has been created and seemingly closed.  You drop back to the main Slides menu and then this:

INFO     Creating output directory.
INFO     Initializing
INFO     ===== validate() ======
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     ===== initialize() ======
INFO     local_dir=/Users/jamhar03/.workload_automation/dependencies/googleslides, local_file=None
INFO     device_dir=/sdcard/wa-working/../Download, wa_test_file=None
INFO     Running workload 1 googleslides (iteration 1)
INFO        Setting up
INFO     ===== setup() ======
INFO        Executing
INFO     ===== run() ======
ERROR    Error while running workload:
ERROR       INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.googleslides.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googleslides.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: Could not find view with text: UX Perf Slides
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:345)
ERROR       at com.arm.wlauto.uiauto.googleslides.UiAutomation.deleteDocument(UiAutomation.java:369)
ERROR       at com.arm.wlauto.uiauto.googleslides.UiAutomation.testEditNewSlidesDocument(UiAutomation.java:310)
ERROR       at com.arm.wlauto.uiauto.googleslides.UiAutomation.runUiAutomation(UiAutomation.java:95)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.googleslides.UiAutomation
ERROR    INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Could not find view with text: UX Perf Slides
ERROR       at com.arm.wlauto.uiauto.BaseUiAutomation.getUiObjectByText(BaseUiAutomation.java:345)
ERROR       at com.arm.wlauto.uiauto.googleslides.UiAutomation.deleteDocument(UiAutomation.java:369)
ERROR       at com.arm.wlauto.uiauto.googleslides.UiAutomation.testEditNewSlidesDocument(UiAutomation.java:310)
ERROR       at com.arm.wlauto.uiauto.googleslides.UiAutomation.runUiAutomation(UiAutomation.java:95)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Test results for WatcherResultPrinter=.E
ERROR    Time: 128.788
ERROR  
ERROR    FAILURES!!!
ERROR    Tests run: 1,  Failures: 0,  Errors: 1
ERROR  
ERROR  
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR  
INFO        Processing result

**Comment by muendelezaji** [comment]
Is this failing consistently on that device? Could we get a screenshot of the device at this point?

Off the top of my head, I can think of one scenario where this might happen - if the name of the PowerPoint file does not fully appear on the homescreen, e.g. it appears as `UX Pe...ides.pptx` then UIAutomator will fail to find the view.

If that is indeed the case a potential solution would be to use a shorter name. Something like `UX.pptx` should do for just about all devices.
